Engine:
    Resources: .\engineResources\
Window:
# Blog header image size: 2000 x 800
    Width: 400
    Height: 300
Camera:
    Position: [0, 0, 0]
    FOV: 70.0
    RenderMode: 0
    # Skybox: dc59842d-3530-47a8-bb22-acc400f8b930 # Debug Skybox
    Skybox: a5dfbc43-582b-46cf-9416-e853b21cae07 # Stormy Days