Engine:
    Resources: .\engineResources\
    Project: .\exampleProject\
Window:
# Blog header image size: 2000 x 800
    Width: 800
    Height: 600
Camera:
    Position: [0, 0, 0]
    FOV: 70.0
    Skybox: dc59842d-3530-47a8-bb22-acc400f8b930